# -*- coding: utf-8 -*-
"""downloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14TAhs2RCoAs9L3DzP_FWRHZxnnBy4S82
"""

from google.colab import drive
drive.mount('/content/drive')

url = input('Enter URL:\n')

import requests
import time
import os
r = requests.get(url,stream=True)
name = url.split('/')
file_name = name[-1].replace("%20" , " ")
total_size_in_bytes= int(r.headers.get('content-length', 0))

if not total_size_in_bytes:
  print("ERROR, something went wrong")
else:
  start = time.time()
  total_size = 0
  path = "/content/drive/My Drive/Movies/"

  print("File Name = %s" %(file_name))
  if total_size_in_bytes/1000 < 1000:
    print("Total File Size = %d KB \n" %(int(total_size_in_bytes/1024)))
  else:
    print("Total File Size = %.2f MB \n" %(total_size_in_bytes/(1024*1024)))

  print("Starting download %s ..." %(file_name))
  i=0
  if os.path.exists(path+file_name):
    split_name = file_name.split('.')
    last_name_part = split_name[-2]
    while os.path.exists(path+file_name):
      i+=1
      split_name = file_name.split('.')
      split_name[-2] = last_name_part + f"({i})"
      file_name = '.'.join(split_name)


  with open(path+ file_name, "wb") as file:

    tic = time.perf_counter()
    
    for block in r.iter_content(chunk_size = 1024):
      if block:
        file.write(block)
        total_size += len(block)
        done = (100 * total_size / total_size_in_bytes)
        
        toc = time.perf_counter()
        if toc - tic >= 5:
          tic = toc
          print('%.2f%% Complete , Download Speed %.1f kb/s' % (done ,(total_size/(time.time() - start))/1024))  
    

    if total_size_in_bytes != 0 and total_size != total_size_in_bytes:
      print("ERROR, something went wrong")
    else:
      print("Download Compelete Time Elapsed: %d Minutes and %d Seconds \n" % (int((time.time()-start)//60), int((time.time()-start)%60)))